# Generated by Django 6.1 on 2026-09-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('track', models.PositiveSmallIntegerField()),
                ('position', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
