# Generated by Django 6.1 on 2026-09-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_starred_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_star_project', 'Can Star Project')]},
        ),
    ]
