# Generated by Django 6.1 on 2026-09-26 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_project_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AddField(
            model_name='achievement',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_achievements', to=settings.AUTH_USER_MODEL),
        ),
    ]
